const express=require("express"); const {z}=require("zod"); const {pool}=require("../db/pool"); const asyncHandler=require("../utils/asyncHandler"); const {authenticateToken,requireRoles}=require("../middleware/authMiddleware"); const {validateRequest}=require("../middleware/validateRequest"); const {validateParams}=require("../middleware/validateParams"); const {createAuditLog}=require("../services/auditService"); const {getCounsellorAvailability}=require("../services/availabilityService");
const router=express.Router(); router.use(authenticateToken); router.use(requireRoles("counsellor"));
const windowSchema=z.object({windows:z.array(z.object({dayOfWeek:z.number().int().min(0).max(6),startTime:z.string().regex(/^\d{2}:\d{2}$/),endTime:z.string().regex(/^\d{2}:\d{2}$/),enabled:z.boolean()}).refine(v=>!v.enabled||v.endTime>v.startTime,{message:"End time must be after start time."})).length(7),timezone:z.string().trim().min(3).max(100),defaultSessionDurationMinutes:z.number().int().min(15).max(180)}).strict();
const blockSchema=z.object({startsAt:z.string().datetime(),endsAt:z.string().datetime(),reason:z.string().trim().max(500).optional().or(z.literal(""))}).refine(v=>new Date(v.endsAt)>new Date(v.startsAt),{message:"Block end must be after start."}); const id=z.object({blockId:z.string().uuid()}).strict();
function map(a){return {isAvailable:Boolean(a.profile?.is_available),timezone:a.profile?.availability_timezone||'Asia/Kolkata',defaultSessionDurationMinutes:Number(a.profile?.default_session_duration_minutes||60),windows:a.windows.map(w=>({id:w.id,dayOfWeek:w.day_of_week,startTime:String(w.start_time).slice(0,5),endTime:String(w.end_time).slice(0,5),enabled:w.is_enabled})),blocks:a.blocks.map(b=>({id:b.id,startsAt:b.starts_at,endsAt:b.ends_at,reason:b.reason}))}}
router.get('/',asyncHandler(async(req,res)=>res.json({success:true,availability:map(await getCounsellorAvailability(req.user.id))})));
router.put('/',validateRequest(windowSchema),asyncHandler(async(req,res)=>{const c=await pool.connect();try{await c.query('BEGIN');const b=req.validatedBody;await c.query('UPDATE counsellor_profiles SET availability_timezone=$1,default_session_duration_minutes=$2,updated_at=NOW() WHERE user_id=$3',[b.timezone,b.defaultSessionDurationMinutes,req.user.id]);for(const w of b.windows)await c.query(`INSERT INTO counsellor_availability_windows(counsellor_id,day_of_week,start_time,end_time,is_enabled) VALUES($1,$2,$3,$4,$5) ON CONFLICT(counsellor_id,day_of_week) DO UPDATE SET start_time=EXCLUDED.start_time,end_time=EXCLUDED.end_time,is_enabled=EXCLUDED.is_enabled,updated_at=NOW()`,[req.user.id,w.dayOfWeek,w.startTime,w.endTime,w.enabled]);await createAuditLog({actorUserId:req.user.id,action:'COUNSELLOR_AVAILABILITY_UPDATED',entityType:'counsellor_profile',entityId:req.user.id,newValues:{timezone:b.timezone,duration:b.defaultSessionDurationMinutes},ipAddress:req.ip,userAgent:req.get('user-agent'),dbClient:c});await c.query('COMMIT');res.json({success:true,message:'Availability schedule saved.',availability:map(await getCounsellorAvailability(req.user.id))});}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}));
router.post('/blocks',validateRequest(blockSchema),asyncHandler(async(req,res)=>{const b=req.validatedBody;const r=await pool.query('INSERT INTO counsellor_unavailability_blocks(counsellor_id,starts_at,ends_at,reason) VALUES($1,$2,$3,$4) RETURNING *',[req.user.id,b.startsAt,b.endsAt,b.reason||null]);res.status(201).json({success:true,message:'Unavailable period added.',block:{id:r.rows[0].id,startsAt:r.rows[0].starts_at,endsAt:r.rows[0].ends_at,reason:r.rows[0].reason}})}));
router.delete('/blocks/:blockId',validateParams(id),asyncHandler(async(req,res)=>{const r=await pool.query('DELETE FROM counsellor_unavailability_blocks WHERE id=$1 AND counsellor_id=$2 RETURNING id',[req.validatedParams.blockId,req.user.id]);if(!r.rowCount)return res.status(404).json({success:false,message:'Unavailable period not found.'});res.json({success:true,message:'Unavailable period removed.'})})); module.exports=router;
