import { Navigate, useNavigate } from 'react-router-dom'
import { getStoredUser } from '../services/api'

function getPortalPath() {
  const currentUser = getStoredUser()
  if (!currentUser) return '/'
  if (currentUser.role === 'admin') return '/admin/overview'
  if (currentUser.role === 'counsellor') return '/counsellor/dashboard'
  return '/app/dashboard'
}

function PublicHome() {
  const navigate = useNavigate()
  const currentUser = getStoredUser()
  if (currentUser) return <Navigate to={getPortalPath()} replace />

  function beginService(service: 'career_counselling' | 'mock_interview') { navigate(`/register?service=${service}`) }

  return <main>
    <section className="hero-section" id="home"><div className="hero-content"><p className="eyebrow">CAREER GUIDANCE MADE PRACTICAL</p><h1>Take the next step<span> in your career.</span></h1><p className="hero-description">Get personalised support when you need it, or use practical frameworks to prepare your next career move.</p><div className="hero-actions"><a className="primary-button" href="#services">Get personalised support</a><a className="text-button" href="#career-toolkit">Explore the Career Toolkit <span>→</span></a></div><div className="hero-stats"><div><strong>1:1</strong><span>Personal guidance</span></div><div><strong>2</strong><span>Support services</span></div><div><strong>Free</strong><span>Career starter resources</span></div></div></div><div className="hero-panel"><div className="panel-label">YOUR CAREER JOURNEY</div><div className="journey-step active"><span className="step-number">01</span><div><strong>Explore support or resources</strong><p>Start with your immediate need</p></div><span className="step-check">✓</span></div><div className="journey-line"/><div className="journey-step"><span className="step-number">02</span><div><strong>Create your free account</strong><p>Keep requests and tools together</p></div></div><div className="journey-line"/><div className="journey-step"><span className="step-number">03</span><div><strong>Take the next step</strong><p>Request tailored guidance when ready</p></div></div><div className="panel-note"><span>✦</span> Start with one useful action today.</div></div></section>

    <section className="services-section" id="services"><div className="section-heading"><p className="eyebrow">PERSONALISED SUPPORT</p><h2>Choose what you need right now.</h2><p>Start with a service. We preserve your choice through account creation, then take you directly to the request form using the same email you register or log in with.</p></div><div className="service-grid"><article className="service-card"><div className="service-icon">✦</div><p className="service-type">GUIDANCE SESSION</p><h3>Career Counselling</h3><p>Get help with career direction, role transition, CV improvement, job-search planning, and interview preparation.</p><ul><li>Career direction and next steps</li><li>CV and profile feedback</li><li>Job-search planning</li></ul><button className="service-button" type="button" onClick={() => beginService('career_counselling')}>Request Career Counselling <span>→</span></button></article><article className="service-card featured-card"><div className="featured-badge">MOST REQUESTED</div><div className="service-icon">◎</div><p className="service-type">PRACTICE SESSION</p><h3>Mock Interview</h3><p>Practise your interview in a realistic format and receive focused feedback on answers, confidence, and communication.</p><ul><li>Technical or HR interview practice</li><li>Answer and communication feedback</li><li>Preparation recommendations</li></ul><button className="service-button dark-button" type="button" onClick={() => beginService('mock_interview')}>Request Mock Interview <span>→</span></button></article></div></section>

    <section className="how-it-works-section" id="how-it-works"><div className="section-heading compact-heading"><p className="eyebrow">HOW IT WORKS</p><h2>Start with your need or your account.</h2></div><div className="process-grid"><div className="process-card"><span>01</span><h3>Choose your path</h3><p>Request support first, or create your free CareerConnect account and explore the Career Toolkit.</p></div><div className="process-card"><span>02</span><h3>Share what you need</h3><p>Choose Career Counselling or Mock Interview, then describe your goal in the secure portal.</p></div><div className="process-card"><span>03</span><h3>Track every update</h3><p>See assignment, messages, sessions, and feedback in one private workspace.</p></div></div></section>

    <section className="services-section" id="career-toolkit"><div className="section-heading"><p className="eyebrow">CAREER TOOLKIT</p><h2>Practical frameworks for your next move.</h2><p>Open resources that help you prepare now. Create a free account to keep your requests and future tailored support in one place.</p></div><div className="service-grid"><article className="service-card"><div className="service-icon">↗</div><p className="service-type">CAREER DIRECTION</p><h3>Career Direction Framework</h3><p>Clarify where you are, what work you want next, and the skills or experience you need to close the gap.</p></article><article className="service-card"><div className="service-icon">★</div><p className="service-type">INTERVIEW PREPARATION</p><h3>STAR Answer Planner</h3><p>Turn your real work into focused situation, task, action, and result stories for interviews.</p></article><article className="service-card"><div className="service-icon">✓</div><p className="service-type">RESUME AND PROFILE</p><h3>Impact Statement Checklist</h3><p>Write stronger resume and LinkedIn achievements using outcome, scope, action, and evidence.</p></article><article className="service-card"><div className="service-icon">◎</div><p className="service-type">JOB SEARCH</p><h3>Weekly Job Search Planner</h3><p>Create a repeatable weekly plan for research, networking, applications, and follow-up.</p></article></div><div className="login-prompt-section"><div><p className="eyebrow">READY FOR TAILORED HELP?</p><h2>Create a free account, then request support when you need it.</h2><p>Existing users can submit another support request at any time from My Workspace.</p></div><button className="primary-button button-reset" type="button" onClick={() => navigate('/register')}>Create free account</button></div></section>
  </main>
}

export default PublicHome
